### ISSUE TITLE
多个nn，dn节点是不是需要启动多个服务来监控啊

### ISSUE THREAD

**Issue by yhz1985** [zqyangchn/hadoop_exporter#1]
请问如果是多个nn，dn节点，是不是需要启动多个进程来监控啊?
我试了下，在一个进程里面写入多个地址，只有一个地址是生效的。

**Comment by zqyangchn** [comment]
对、每个nn、dn需要一个exporter

yhz110 <notifications@github.com>于2020年12月30日 周三16:50写道：
